apiVersion: v1
kind: Secret
metadata:
  name: {{ include "win_k8s.fullname" . }}-secret
  labels:
    {{- include "win_k8s.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Backend secrets
  MONGODB_URI: {{ .Values.backend_secrets.MONGODB_URI | quote }}
  JWT_SECRET: {{ .Values.backend_secrets.JWT_SECRET | quote }}
  JWT_EXPIRE: {{ .Values.backend_secrets.JWT_EXPIRE | quote }}
  EMAIL_HOST: {{ .Values.backend_secrets.EMAIL_HOST | quote }}
  EMAIL_PORT: {{ .Values.backend_secrets.EMAIL_PORT | quote }}
  EMAIL_USER: {{ .Values.backend_secrets.EMAIL_USER | quote }}
  EMAIL_PASSWORD: {{ .Values.backend_secrets.EMAIL_PASSWORD | quote }}
  EMAIL_FROM: {{ .Values.backend_secrets.EMAIL_FROM | quote }}
  ADMIN_EMAIL: {{ .Values.backend_secrets.ADMIN_EMAIL | quote }}
  ADMIN_PASSWORD: {{ .Values.backend_secrets.ADMIN_PASSWORD | quote }}
  AZURE_OPENAI_ENDPOINT: {{ .Values.backend_secrets.AZURE_OPENAI_ENDPOINT | quote }}
  AZURE_OPENAI_API_KEY: {{ .Values.backend_secrets.AZURE_OPENAI_API_KEY | quote }}
